### ISSUE TITLE
[Suggestion] Prepared statement

### ISSUE THREAD

**Issue by Gounlaf** [byjg/anydataset-db#1]
Hi,

I have suggestion about prepared statement: IMO, prepared statement object (`PDOStatement`) should be stored (in a "cache") and reused while the PDO instance is still the same.
Looking at method `DbProDiver::getDBStatement`, an SQL request is always prepared

https://github.com/byjg/anydataset-db/blob/3fffd5612f3991cf8eefc5f17e0062c2180d989d/src/DbPdoDriver.php#L110-L123

A really simple implementation might be like this.

```php
$stmt = $this->cache->has($sql) ? $this->cache->get($sql) : $this->instance->prepare($sql);
```

Cache would be:
* a "simple memory cache" (an associative array with SQL statement - as string - for key?); 
* destroyed everytime pdo instance change

What do you think about it?

Regards

**Comment by byjg** [comment]
I think your comment is totally valid and now with the PSR-16 / PSR-6 specification it will be easy to do. 

Until the weekend I can do something on it.

**Comment by Gounlaf** [comment]
Hi!
That's would be very nice.

I'm not sure that all type of cache can be supported (depends on the serialization capability of the PDOStatement object).

Tell me If i can help you,

Thanks

**Comment by byjg** [comment]
It would be awesome if you can check if the statement can be serialized before we dig into too much.

**Comment by Gounlaf** [comment]
Sure!

**Comment by Gounlaf** [comment]
@byjg https://github.com/php/php-src/commit/28edeb2ba3551fc6cff2db0004d67435467cdaac
Yup, not serializable at all

**Comment by byjg** [comment]
OK, so let's use your initial idea. It will simpler.

**Comment by Gounlaf** [comment]
> OK, so let's use your initial idea. It will be simpler.
I can take a look to Doctrine or Eloquent to see how they do.

**Comment by Gounlaf** [comment]
> I can take a look to Doctrine or Eloquent to see how they do.

It's hard to determine if there are such mechanism or not. I saw an old commit about it (2016) which is outdated.

**Comment by byjg** [comment]
OK, i implemented something based on what you proposed. https://github.com/byjg/anydataset-db/commit/17f6f361a1f60d55d9461d7a585af4cf961f580c . I believe it is safe to proceed.

**Comment by Gounlaf** [comment]
Hi !
You have forgotten the reset of the cache.
I think it should be done both in the createPdo method and the destructor too

**Comment by Gounlaf** [comment]
Hi @byjg,

Have you some time to finish it?
I can fork and help you finish what is missing if you want.

Regards,

**Comment by byjg** [comment]
I am so sorry, I missed your last message. Well, I believe is not necessary reset the cache as the property is `protected` and we have an empty value every new instance. 

https://github.com/byjg/anydataset-db/commit/17f6f361a1f60d55d9461d7a585af4cf961f580c#diff-7d5efd01d07af1852c9928d2e080d6d7R23

Did I forgot something?

**Comment by Gounlaf** [comment]
> I am so sorry, I missed your last message.

No problems :)

> Well, I believe is not necessary reset the cache as the property is `protected` and we have an empty value every new instance.
> 
> [17f6f36#diff-7d5efd01d07af1852c9928d2e080d6d7R23](https://github.com/byjg/anydataset-db/commit/17f6f361a1f60d55d9461d7a585af4cf961f580c#diff-7d5efd01d07af1852c9928d2e080d6d7R23)
> 
> Did I forgot something?

I got your point. I just think it would be safer to set at the beginning of `createPdoInstance` :
```php
$this->stmtCache = []
```

And in the destructor, I would nullify the cache first, then the pdo instance... but I don't think it really matters xD

**Comment by Gounlaf** [comment]
Hi @byjg,

Any news?

Thanks

**Comment by byjg** [comment]
I implemented all of your suggestions. I'll open a PR and I believe we can discuss in the code, if something is missing.
